### ISSUE TITLE
Always connect failed

### ISSUE THREAD

**Issue by Charliego3** [mzyy94/gocarplay#3]
I'm run the demo proj, but always connect failed

- MacOS: `12.1`
- Go: `1.17.5`
- Safari: `15.2`

```shell
2022/01/05 14:35:09 http://localhost:8001
2022/01/05 14:36:34 State of PeerConnection-1641364571738669000: checking 
2022/01/05 14:37:04 State of PeerConnection-1641364571738669000: failed 
2022/01/05 14:37:32 State of PeerConnection-1641364644202443000: checking 
2022/01/05 14:38:14 State of PeerConnection-1641364644202443000: failed
```

**Comment by mzyy94** [comment]
Oh, I checked same issue on Safari. but I couldn't able to find a bug on WebRTC layer between this project and Safari connection.
A WebRTC demo is a simple demo in order to check a behavior of main module. Please use Chrome for checking it. 😭
